language: android
sudo: false
android:
  components:
   - build-tools-23.0.1
   - android-23
   - extra-android-m2repository
   - extra-android-support
script:
   - ./gradlew assembleDebug
before_deploy:
   - mv app/build/outputs/apk/app-debug.apk app/build/outputs/apk/DataBindingSample.apk
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_ACCESS_TOKEN
  file: app/build/outputs/apk/DataBindingSample.apk
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - gem install fir-cli
  - fir p app/build/outputs/apk/DataBindingSample.apk -T 0b9a1c25f61439882dcb93f0f16c2f0b -c "'git log -n 1'"