language: android
sudo: false
android:
  components:
   - build-tools-23.0.1
   - android-23
   - extra-android-m2repository
   - extra-android-support
script:
  - ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
      secure: 52372b56db1bba3dddb9175bfe27c88422891fda
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true