language: android
sudo: false
android:
  components:
   - build-tools-23.0.1
   - android-23
   - extra-android-m2repository
   - extra-android-support
script:
   - ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
