language: android
sudo: false
android:
  components:
   - build-tools-23.0.1
   - android-23
   - extra-android-m2repository
   - extra-android-support
script:
   - ./gradlew assembleRelease
   - gem install fir-cli
   - fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"

