language: android
sudo: false
android:
  components:
   - build-tools-23.0.1
   - android-23
   - extra-android-m2repository
   - extra-android-support
script:
   - ./gradlew assembleRelease
before_install:
   - gem install fir-cli
deploy:
  provider: releases
  user: jingle1267
  password:
    secure: $GITHUB
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - fir p app/build/outputs/apk/app-release.apk -T 0b9a1c25f61439882dcb93f0f16c2f0b -c "'git log -n 1'"
